#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NVIM_TARGET=~/.config/nvim
WEZTERM_TARGET=~/.config/wezterm
STARSHIP_TARGET=~/.config/starship.toml

NVIM_SOURCE="$DIR/nvim"
WEZTERM_SOURCE="$DIR/wezterm"
STARSHIP_SOURCE="$DIR/starship/starship.toml"

echo "Removing existing config files..."
rm -rf "$NVIM_TARGET"
rm -rf "$WEZTERM_TARGET"
rm -f "$STARSHIP_TARGET"

echo "Creating symlinks..."
ln -s "$NVIM_SOURCE" "$NVIM_TARGET"
ln -s "$WEZTERM_SOURCE" "$WEZTERM_TARGET"
ln -s "$STARSHIP_SOURCE" "$STARSHIP_TARGET"

echo "✅ Config symlinks set up successfully from $DOTFILES_DIR."

